services:
  litserve:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./.env:/app/.env:ro
  postgres:
    image: pgvector/pgvector:0.8.0-pg17-bookworm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vectordb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # neo4j:
  #   image: neo4j:5.26.10
  #   volumes:
  #     - ./neo4j-data:/data:rw
  #     - ./neo4j-import:/import:rw
  #     - ./neo4j-conf:/conf:rw
  #   restart: always
  #   environment:
  #     - NEO4J_AUTH=neo4j/neo4jneo4j
  #   ports:
  #     - 7687:7687
  #     - 7474:7474
  #   healthcheck:
  #     test: ["CMD-SHELL", "cypher-shell", "match (n) return count(n)"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 10s